### PR TITLE
add starter code for prework project

### PR DESCRIPTION
**Pull request by anna071387**
added started code and fixed html bug in header.

### CODE REVIEW

**Review by anna071387 — COMMENTED** [review]
Everything is up to date

**Review by anna071387 — COMMENTED** [review]
Great Work

**Review by anna071387 — COMMENTED** [review]
Reviewed

**Comment by anna071387** [comment]
REsubmitt

**Review by glamdrella — APPROVED** [review]
Approved

**Review by glamdrella — APPROVED** [review]
Reviewed

**Comment by glamdrella** [comment]
Ready to close

**Review by glamdrella — COMMENTED** [review]
Reviewed

**Review by anna071387 — COMMENTED** [review]
Complete

**Review by anna071387 — COMMENTED** [review]
got it

**Pull request closed without merging**
